import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getAIConfig, generateAIContent } from '@/lib/ai';

export async function POST(request: Request) {
  try {
    // Basic auth check (can be expanded for secure cron trigger)
    const authHeader = request.headers.get('authorization');
    const isCron = authHeader === `Bearer ${process.env.CRON_SECRET}`;
    
    // Check if auto-blogging is active
    const settings = await prisma.autoBlogSettings.findUnique({ where: { id: 'default' } });
    if (!settings?.isActive && !isCron) {
      // If triggered manually from admin, we might bypass the isActive check, but let's assume it should be active.
      // Actually, allow manual triggers even if paused.
    }

    // 1. Fetch next pending keyword
    const pendingKeyword = await prisma.autoBlogKeyword.findFirst({
      where: { status: 'pending' },
      orderBy: [
        { priority: 'desc' },
        { createdAt: 'asc' }
      ]
    });

    if (!pendingKeyword) {
      return NextResponse.json({ message: 'No pending keywords found in queue.', status: 'empty' });
    }

    const aiConfig = await getAIConfig();
    if (!aiConfig) {
      return NextResponse.json({ error: 'AI Provider not configured.' }, { status: 400 });
    }

    // 2. Generate Content
    const topic = pendingKeyword.keyword;
    
    // Generate Title
    const titlePrompt = 'You are an expert SEO copywriter. Generate 1 highly engaging, click-worthy, SEO-optimized blog post title for the given topic. Return ONLY the title, no quotes, no extra text.';
    const rawTitle = await generateAIContent(aiConfig, titlePrompt, `Topic: ${topic}`, 100);
    const title = rawTitle.replace(/^["']|["']$/g, '').trim();

    // Generate Article
    const articlePrompt = 'You are an expert blog writer. Write a comprehensive, SEO-optimized article (1000+ words). Use appropriate HTML formatting (h2, h3, p, ul, li, strong, em). Ensure the tone is professional yet engaging. Do not include a title tag (h1), start with an h2 or introductory paragraph. Return ONLY the HTML content.';
    const content = await generateAIContent(aiConfig, articlePrompt, `Title: ${title}\nTopic: ${topic}`, 4000);

    // Generate SEO metadata
    const seoPrompt = 'You are an SEO expert. Given the blog content, generate an SEO title, an SEO description (under 160 characters), and a comma-separated list of keywords. Format exactly as:\nSEO Title: [title]\nSEO Description: [desc]\nKeywords: [kw]';
    const seoRaw = await generateAIContent(aiConfig, seoPrompt, content.substring(0, 2000), 300);
    
    let seoTitle = title;
    let seoDescription = '';
    let seoKeywords = pendingKeyword.keyword;

    const titleMatch = seoRaw.match(/SEO Title:\s*(.*)/i);
    const descMatch = seoRaw.match(/SEO Description:\s*(.*)/i);
    const kwMatch = seoRaw.match(/Keywords:\s*(.*)/i);

    if (titleMatch && titleMatch[1]) seoTitle = titleMatch[1].trim();
    if (descMatch && descMatch[1]) seoDescription = descMatch[1].trim();
    if (kwMatch && kwMatch[1]) seoKeywords = kwMatch[1].trim();

    // Excerpt
    const excerpt = seoDescription || content.substring(0, 150).replace(/<[^>]+>/g, '') + '...';

    // 3. Featured Image (Unsplash)
    let featuredImage = null;
    if (settings?.imageSource === 'unsplash') {
      const encodedTopic = encodeURIComponent(pendingKeyword.niche || topic.split(' ')[0] || 'business');
      // Using Source Unsplash which returns a random image matching terms
      featuredImage = `https://source.unsplash.com/1200x630/?${encodedTopic}`;
    }

    // 4. Create Post
    let slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
    const existing = await prisma.blogPost.findUnique({ where: { slug } });
    if (existing) slug = `${slug}-${Date.now()}`;

    const superAdmin = await prisma.user.findFirst({ where: { role: 'SUPER_ADMIN' } });

    const post = await prisma.blogPost.create({
      data: {
        title,
        slug,
        content,
        excerpt,
        featuredImage,
        status: settings?.autoPublish ? 'Published' : 'Draft',
        publishedAt: settings?.autoPublish ? new Date() : null,
        autoGenerated: true,
        seoTitle,
        seoDescription,
        seoKeywords,
        authorId: superAdmin?.id
      }
    });

    // 5. Update Keyword
    await prisma.autoBlogKeyword.update({
      where: { id: pendingKeyword.id },
      data: { status: 'used', usedAt: new Date(), postId: post.id }
    });

    // 6. Log success
    await prisma.autoBlogLog.create({
      data: {
        keyword: pendingKeyword.keyword,
        title: post.title,
        status: 'success',
        postId: post.id
      }
    });

    // Update last run
    if (settings) {
      await prisma.autoBlogSettings.update({
        where: { id: settings.id },
        data: { lastRunAt: new Date() }
      });
    }

    return NextResponse.json({ success: true, post });
  } catch (error: any) {
    console.error('Auto-blog error:', error);
    
    // Attempt to log failure
    try {
      // Find pending again to log if we crashed during generation
      const pendingKeyword = await prisma.autoBlogKeyword.findFirst({
        where: { status: 'pending' },
        orderBy: [{ priority: 'desc' }, { createdAt: 'asc' }]
      });
      
      if (pendingKeyword) {
        await prisma.autoBlogKeyword.update({
          where: { id: pendingKeyword.id },
          data: { status: 'failed' }
        });
        
        await prisma.autoBlogLog.create({
          data: {
            keyword: pendingKeyword.keyword,
            status: 'failed',
            error: error.message || 'Unknown error'
          }
        });
      }
    } catch (e) {
      // ignore
    }

    return NextResponse.json({ error: 'Auto-blogging failed' }, { status: 500 });
  }
}

export async function GET() {
  try {
    const [totalKeywords, pendingKeywords, usedKeywords, totalAutoPosts, logs] = await Promise.all([
      prisma.autoBlogKeyword.count(),
      prisma.autoBlogKeyword.count({ where: { status: 'pending' } }),
      prisma.autoBlogKeyword.count({ where: { status: 'used' } }),
      prisma.blogPost.count({ where: { autoGenerated: true } }),
      prisma.autoBlogLog.findMany({ orderBy: { createdAt: 'desc' }, take: 5 })
    ]);

    return NextResponse.json({
      stats: {
        totalKeywords,
        pendingKeywords,
        usedKeywords,
        totalAutoPosts
      },
      logs
    });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch stats' }, { status: 500 });
  }
}
