'use client';
import React, { useEffect, useState } from 'react';
import { notFound } from 'next/navigation';
import Head from 'next/head';
import LeadCaptureForm from '@/components/LeadCaptureForm';
import SmartBanners from '@/components/SmartBanners';
import BlogChatbot from '@/components/BlogChatbot';

export default function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = React.use(params);
  const [post, setPost] = useState<any>(null);
  const [ads, setAds] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Fetch post and ads in parallel
    Promise.all([
      fetch(`/api/blog/${slug}`).then(res => res.ok ? res.json() : null),
      fetch('/api/ads').then(res => res.ok ? res.json() : [])
    ]).then(([postData, adsData]) => {
      if (!postData) notFound();
      setPost(postData);
      setAds(Array.isArray(adsData) ? adsData : []);
      setIsLoading(false);
    }).catch(() => {
      setIsLoading(false);
      notFound();
    });
  }, [slug]);

  if (isLoading) {
    return (
      <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ fontSize: '1.5rem', fontWeight: 600, color: 'var(--color-accent)' }}>Loading...</div>
      </div>
    );
  }

  if (!post) return null;

  const headerAd = ads.find(a => a.position === 'header');
  const inContentAd = ads.find(a => a.position === 'in_content');
  const footerAd = ads.find(a => a.position === 'footer');

  // Inject in-content ad after the second paragraph if it exists
  let contentHtml = post.content || '';
  if (inContentAd && inContentAd.adCode) {
    const parts = contentHtml.split('</p>');
    if (parts.length > 2) {
      parts[1] = parts[1] + '</p><div class="ad-container my-8">' + inContentAd.adCode + '</div>';
      contentHtml = parts.join('</p>');
    }
  }

  return (
    <div style={{ background: 'var(--color-bg-primary)', color: 'var(--color-text-primary)' }}>
      <title>{post.seoTitle || post.title}</title>
      <meta name="description" content={post.seoDescription || post.excerpt} />
      {post.seoKeywords && <meta name="keywords" content={post.seoKeywords} />}

      {/* Header Ad */}
      {headerAd && (
        <div className="ad-container" style={{ textAlign: 'center', padding: '1rem', background: 'var(--color-bg-secondary)' }} dangerouslySetInnerHTML={{ __html: headerAd.adCode }} />
      )}

      <article style={{ maxWidth: '800px', margin: '0 auto', padding: '4rem 2rem' }}>
        {/* Post Header */}
        <header style={{ marginBottom: '3rem', textAlign: 'center' }}>
          {post.tags?.length > 0 && (
            <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', marginBottom: '1.5rem' }}>
              {post.tags.map((tag: string) => (
                <span key={tag} style={{ background: 'var(--color-bg-secondary)', padding: '0.4rem 1rem', borderRadius: '20px', fontSize: '0.8rem', fontWeight: 600, color: 'var(--color-accent)' }}>
                  {tag}
                </span>
              ))}
            </div>
          )}
          <h1 style={{ fontSize: '3.5rem', fontWeight: 800, lineHeight: 1.2, letterSpacing: '-1px', marginBottom: '1.5rem' }}>
            {post.title}
          </h1>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '1rem', color: 'var(--color-text-secondary)', fontSize: '0.9rem' }}>
            {post.author?.name && (
              <span style={{ fontWeight: 600, color: 'var(--color-text-primary)' }}>{post.author.name}</span>
            )}
            <span>•</span>
            <time>{new Date(post.publishedAt || post.createdAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</time>
            <span>•</span>
            <span>{Math.ceil((post.content?.length || 0) / 1000)} min read</span>
            {post.autoGenerated && (
              <>
                <span>•</span>
                <span style={{ background: '#f3e8ff', color: '#9333ea', padding: '0.2rem 0.6rem', borderRadius: '4px', fontSize: '0.75rem', fontWeight: 600 }}>✨ AI Generated</span>
              </>
            )}
          </div>
        </header>

        {/* Featured Image */}
        {post.featuredImage && (
          <figure style={{ margin: '0 -2rem 3rem', borderRadius: '24px', overflow: 'hidden', boxShadow: '0 20px 40px rgba(0,0,0,0.1)' }}>
            <img src={post.featuredImage} alt={post.title} style={{ width: '100%', height: 'auto', display: 'block' }} />
          </figure>
        )}

        {/* Post Content */}
        <div 
          className="blog-content"
          style={{ fontSize: '1.1rem', lineHeight: 1.8, color: '#374151' }}
          dangerouslySetInnerHTML={{ __html: contentHtml }} 
        />

        {/* Smart Banners */}
        <SmartBanners />

        {/* Lead Capture */}
        <div style={{ marginTop: '4rem' }}>
          <LeadCaptureForm postId={post.id} />
        </div>

        {/* Footer Ad */}
        {footerAd && (
          <div className="ad-container" style={{ textAlign: 'center', marginTop: '3rem' }} dangerouslySetInnerHTML={{ __html: footerAd.adCode }} />
        )}
      </article>

      {/* Floating Chatbot */}
      <BlogChatbot postTitle={post.title} postContent={post.content} />

      <style>{`
        .blog-content h2 { fontSize: 2rem; fontWeight: 700; margin: 2.5rem 0 1rem; color: #111827; letter-spacing: -0.5px; }
        .blog-content h3 { fontSize: 1.5rem; fontWeight: 600; margin: 2rem 0 1rem; color: #1f2937; }
        .blog-content p { margin-bottom: 1.5rem; }
        .blog-content ul { margin: 0 0 1.5rem 2rem; list-style-type: disc; }
        .blog-content li { margin-bottom: 0.5rem; }
        .blog-content strong { color: #111827; }
        .blog-content a { color: var(--color-accent); text-decoration: none; border-bottom: 1px solid transparent; transition: border-color 0.2s; }
        .blog-content a:hover { border-bottom-color: var(--color-accent); }
        .blog-content blockquote { border-left: 4px solid var(--color-accent); margin: 2rem 0; padding-left: 1.5rem; font-style: italic; color: #4b5563; }
      `}</style>
    </div>
  );
}
